### PR TITLE
48 some minor js docs and styling fixes

### LINKED ISSUE #48: Some minor JSDocs and styling fixes
### Description
Fix some minor issues in the JSDocs and add some for the icon components. Fix some minor styling issues related to the app container and the side-pane/navbar components.

- [ ] JSDocs for Icon components
- [ ] Fix navbar and side-panes detaching from each other in smaller displays
image

- [ ] Fix side-pane component props
- [ ] Fix main app container width restrictions
image

### PR DESCRIPTION
**Pull request by paulmmaingi**
### Description
Fix some minor issues in the JSDocs and add some for the icon components. Fix some minor styling issues related to the app container and the side-pane/navbar components.

- [x] JSDocs for Icon components
- [x] Fix navbar and side-panes detaching from each other in smaller displays
image

- [x] Fix side-pane component props
- [x] Fix main app container width restrictions
image

### Notes
In the Graph view, the display width will have to be adjusted (made reactive) to take into account expanded/collapsed side-panes.

### Linked issues
Closes #48

### CODE REVIEW

File: src/client/src/components/GraphInfoSidepane.vue [hunk 1]
```diff
@@ -1,74 +1,62 @@
...
-      <p class="right-text">Right Sidepanel</p>
-      <button class="right-btn" @click="toggleRightNav">&#9776;</button>
-    </div>
+    <button class="right-btn" @click="toggleRightNav">&#9776;</button>
+    <p class="right-text">Right Sidepanel</p>
   </div>
 </template>
 
 <style scoped>
 .right-sidepanel {
```
Comment (keyman015) [inline src/client/src/components/GraphInfoSidepane.vue:49]: image

It seems that the window can shrunk to the point that the side panels can interfere. I don't think this is intended behavior.

**Review by keyman015 — CHANGES_REQUESTED** [review]
Looks amazing. Just found one bug when decreasing the window size on the side panels.

File: src/client/src/components/GraphInfoSidepane.vue (hunk 1 above)
Comment (paulmmaingi) [reply src/client/src/components/GraphInfoSidepane.vue:49]: It did seem like making the side-panels reactive was out of the scope of this PR since we'd also have to decide whether or not and how to display what will be contained in the side-panels (search bar, info of classes, toggles) when the display reaches a certain minimum size.

Comment (keyman015) [reply src/client/src/components/GraphInfoSidepane.vue:49]: Ah. My bad, didn't realise it was out of the scope. LGTM then.

**Review by keyman015 — APPROVED** [review]
